name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools wheel twine commitizen bump2version python-semantic-release

      # - name: Lint commit messages
      #   run: |
      #     ~/.local/bin/commitizen check

      - name: Determine next version
        id: determine_version
        run: |
          VERSION=$(python -m semantic_release version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        run: |
          bump2version --new-version ${{ env.VERSION }} --allow-dirty --verbose setup.py pyproject.toml

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        run: |
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release publish
